service: fitxa_cae
servers:
  web:
    hosts:
    - fitxa-cae.compila.cat
proxy:
  hosts:
  - fitxa.cae.cat
  - fitxar.cae.cat
env:
  clear:
    APP_NAME: FitxaCAE
    APP_HOST: fitxa.cae.cat
    APP_SLUG: fitxa-cae
    APP_BRAND_SUFFIX_IMAGE: cae_logo_trimmed.png
    APP_REDIRECT_HOSTS: fitxar.cae.cat
    LINK_BUTTON_HREF: https://fitxa-xarranca.cae.cat/login
    LINK_BUTTON_TEXT: FitxaXarranca

    HUMAN_RESOURCES_EMAIL: rrhh@cae.cat
    LEGAL_NOTICE_URL: https://cae.cat/avisos-legals/
    MAILER_FROM_EMAIL: FitxaCAE <fitxa@cae.cat>
    ERROR_NOTIFICATION_RECIPIENTS: eric@ericroy.net

    LABSMOBILE_SENDER: FitxaCAE
    SMTP_ADDRESS: mail.cae.cat
    SMTP_PORT: 465
    SMTP_OPENSSL_VERIFY_MODE: none
volumes:
- fitxa_cae_storage:/rails/storage
