service: fitxa_xarranca
servers:
  web:
    hosts:
    - fitxa-cae.compila.cat
proxy:
  host: fitxa-xarranca.cae.cat
env:
  clear:
    APP_NAME: FitxaXarranca
    APP_HOST: fitxa-xarranca.cae.cat
    APP_SLUG: fitxa-xarranca
    APP_FAVICON: fitxa_xarranca_favicon.ico
    APP_ICON_PNG: fitxa_xarranca_icon.png
    APP_ICON_SVG: fitxa_xarranca_icon.svg
    APP_PWA_ICON_192_PNG: fitxa_xarranca_pwa_icon_192.png
    APP_PWA_ICON_PNG: fitxa_xarranca_pwa_icon_512.png
    LINK_BUTTON_HREF: https://fitxa.cae.cat/login
    LINK_BUTTON_TEXT: FitxaCAE

    HUMAN_RESOURCES_EMAIL: rrhh@cae.cat
    LEGAL_NOTICE_URL: https://cae.cat/avisos-legals/
    MAILER_FROM_EMAIL: FitxaXarranca <fitxa-xarranca@cae.cat>
    ERROR_NOTIFICATION_RECIPIENTS: eric@ericroy.net

    LABSMOBILE_SENDER: LaXarranca
    SMTP_ADDRESS: mail.cae.cat
    SMTP_PORT: 465
    SMTP_OPENSSL_VERIFY_MODE: none
volumes:
- fitxa_xarranca_storage:/rails/storage
