service: fitxa_xarranca
servers:
  web:
    hosts:
    - fitxa-cae.compila.cat
proxy:
  host: fitxa-xarranca.cae.cat
env:
  clear:
    APP_NAME: FitxaXarranca
    APP_HOST: fitxa-xarranca.cae.cat
    APP_SLUG: fitxa-xarranca
    APP_FAVICON: fitxa_xarranca_favicon.ico
    APP_ICON_192_PNG: fitxa_xarranca_icon_192.png
    APP_ICON_PNG: fitxa_xarranca_icon.png
    APP_ICON_SVG: fitxa_xarranca_icon.svg
    LINK_BUTTON_HREF: https://fitxa.cae.cat/login
    LINK_BUTTON_TEXT: FitxaCAE
    HUMAN_RESOURCES_EMAIL: rrhh@cae.cat
    LEGAL_NOTICE_URL: https://cae.cat/avisos-legals/
    MAILER_FROM_EMAIL: fitxa@cae.cat
    ERROR_NOTIFICATION_RECIPIENTS: eric@ericroy.net
    ERROR_NOTIFICATION_SENDER: FitxaXarranca <fitxa@cae.cat>
    SMTP_ADDRESS: mail.cae.cat
    LABSMOBILE_SENDER: LaXarranca
    SMTP_DOMAIN: cae.cat
volumes:
- fitxa_xarranca_storage:/rails/storage
