default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: reports
      threads: 1
      processes: <%= ENV.fetch("REPORT_JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1
    - queues:
        - default
        - active_storage_purge
        - active_storage_analysis
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
